- name: 보안 전수 점검 (전체 자동화)
  hosts: target_servers
  become: yes
  tasks:
    - name: 1. 모든 진단 스크립트 목록 가져오기
      delegate_to: localhost
      become: no
      find:
        paths: "./scripts/unix/1_account"
        patterns: "check_*.sh"
      register: script_files

    - name: 2. 발견된 모든 스크립트 실행
      script: "{{ item.path }}"
      register: diag_results
      loop: "{{ script_files.files }}"
      # 'target_id'라는 글자가 파일명에 '포함'되어 있으면 무조건 실행합니다.
      when: >
        target_id is not defined or 
        (target_id | string) in (item.path | basename)

    - name: 3. 결과 수집 (강제 업데이트)
      delegate_to: localhost
      become: no
      copy:
        content: "{{ item.stdout | regex_search('(?s)\\{.*\\}') }}"
        dest: "./results/{{ inventory_hostname }}_{{ item.item.path | basename | replace('.sh', '.json') | replace('-', '') }}"
        # [수정] 기존 파일이 있어도 무조건 새 내용으로 덮어씁니다.
        force: yes 
      loop: "{{ diag_results.results }}"
      when: 
        - item.skipped is not defined
        - "'{' in item.stdout"