- name: 보안 취약점 개별 조치 (대시보드 연동)
  hosts: all
  become: yes
  tasks:
    - name: "1. 조치 대상 변수 확인"
      debug:
        msg: "조치 항목 ID: {{ target_id }}"
      failed_when: target_id is not defined

    - name: "2. 조치 스크립트 실행"
      # target_id가 U01이면 바로 fix_U01.sh를 찾습니다.
      script: "./scripts/unix/1_account/fix_{{ target_id }}.sh -y"
      register: fix_result

     # 3. 조치 로그 저장 (fix_logs)
    - name: "3. 조치 로그 저장"
      delegate_to: localhost
      become: no
      copy:
        content: "{{ fix_result.stdout | regex_search('(?s)\\{.*\\}') }}"
        dest: "/home/manager/security_project/fix_logs/{{ inventory_hostname }}_fix_{{ target_id }}.json"
      when: "'{' in fix_result.stdout"

    - name: "4. 대시보드 즉시 반영 (파일명 구분)"
      delegate_to: localhost
      become: no
      copy:
        content: "{{ fix_result.stdout | regex_search('(?s)\\{.*\\}') }}"
        dest: "/home/manager/security_project/results/{{ inventory_hostname }}_remediated_{{ target_id }}.json"
      when: "'{' in fix_result.stdout"