- name: 보안 취약점 자동 조치 (전체 자동화)
  hosts: target_servers
  become: yes
  tasks:
    - name: 1. 모든 조치 스크립트 목록 가져오기
      delegate_to: localhost
      become: no
      find:
        paths: "./scripts/unix/1_account"
        patterns: "fix_*.sh"
      register: fix_script_files

    - name: 2. 발견된 모든 조치 스크립트 실행
      script: "{{ item.path }}"
      register: fix_results
      loop: "{{ fix_script_files.files }}"

    - name: 3. 조치 결과 무조건 저장 (audit 성공 방식 적용)
      delegate_to: localhost
      become: no
      copy:
        # 아까 audit 때처럼 앞의 빈 줄들을 버리고 JSON 부분만 합쳐서 저장합니다.
        content: "{{ item.stdout_lines[2:] | join('\n') }}"
        dest: "/home/manager/security_project/fix_logs/{{ inventory_hostname }}_{{ item.item.path | basename | replace('.sh', '.json') }}"
      loop: "{{ fix_results.results }}"
      # 출력 결과가 충분히 있을 때만 파일을 만듭니다.
      when: item.stdout_lines | length > 2
