- name: 보안 전수 점검 (Linux & DB 통합 자동화)
  hosts: target_servers
  become: yes
  vars:
    mysql_env_src: "{{ playbook_dir }}/scripts/unix/6_db/mysql/mysql_fix.env"
  tasks:
    - name: "1. OS 및 DB 진단 스크립트 목록 가져오기"
      delegate_to: localhost
      become: no
      find:
        paths: "./scripts/unix"
        patterns: "check_*.sh"
        recurse: yes
      register: script_files

    - name: "1-1. MySQL 접속 환경파일 존재 확인(메인 서버)"
      delegate_to: localhost
      become: no
      stat:
        path: "{{ mysql_env_src }}"
      register: mysql_env_local
      run_once: true

    - name: "1-2. MySQL 접속 환경파일 누락 시 실패"
      delegate_to: localhost
      become: no
      run_once: true
      fail:
        msg: "MySQL 접속 환경파일이 없습니다: {{ mysql_env_src }}"
      when: not mysql_env_local.stat.exists

    - name: "1-3. MySQL 접속 정보 로드(메인 서버)"
      delegate_to: localhost
      delegate_facts: true
      become: no
      run_once: true
      set_fact:
        mysql_user_from_env: >-
          {{ lookup('ansible.builtin.ini', 'MYSQL_USER type=properties file=' ~ mysql_env_src) | default('root', true) | string | trim | trim("'") | trim('"') }}
        mysql_password_from_env: >-
          {{ lookup('ansible.builtin.ini', 'MYSQL_PASSWORD type=properties file=' ~ mysql_env_src) | default('', true) | string | trim | trim("'") | trim('"') }}

    - name: "2. 대상 서버 환경에 맞는 스크립트 실행"
      script: "{{ item.path }}"
      register: diag_results
      loop: "{{ script_files.files }}"
      environment:
        MYSQL_USER: "{{ hostvars['localhost']['mysql_user_from_env'] | default('root') }}"
        MYSQL_PASSWORD: "{{ hostvars['localhost']['mysql_password_from_env'] | default('') }}"
      when: 
        - target_id is not defined or (target_id | string) in (item.path | basename)
        - ("6_db/mysql" not in (item.path | lower)) or ("Rocky9" in inventory_hostname)
        - ("6_db/postgresql" not in (item.path | lower)) or ("Rocky10" in inventory_hostname)

    - name: "3. 결과 수집 및 JSON 저장"
      delegate_to: localhost
      become: no
      copy:
        content: "{{ item.stdout | regex_search('\\{[\\s\\S]*\\}') | default('{}', true) }}"
        dest: "./results/{{ inventory_hostname }}_{{ item.item.path | basename | replace('.sh', '') | replace('-', '') }}.json"
        force: yes 
      loop: "{{ diag_results.results }}"
      when: 
        - item.skipped is not defined or not item.skipped
        - item.stdout is defined and '{' in item.stdout
