- name: 보안 전수 점검 및 조치 자동화
  hosts: target_servers
  become: yes
  vars:
    mysql_env_src: "./scripts/unix/6_db/mysql/mysql_fix.env"
    mysql_env_dest: "/tmp/security_project_mysql_fix.env"
  tasks:
    - name: "1. 조치 스크립트 목록 가져오기"
      delegate_to: localhost
      become: no
      find:
        paths: 
          - "./scripts/unix"
          - "./scripts/db"
        # [수정] check_ 대신 fix_ 로 시작하는 파일을 찾도록 변경!
        patterns: "fix_*.sh"
        recurse: yes
      register: fix_script_files

    - name: "1-1. MySQL 접속 환경파일 존재 확인(메인 서버)"
      delegate_to: localhost
      become: no
      stat:
        path: "{{ mysql_env_src }}"
      register: mysql_env_local
      run_once: true

    - name: "1-2. MySQL 접속 환경파일 대상 서버 배포(Rocky9)"
      copy:
        src: "{{ mysql_env_src }}"
        dest: "{{ mysql_env_dest }}"
        owner: root
        group: root
        mode: "0600"
      when:
        - "'Rocky9' in inventory_hostname"
        - mysql_env_local.stat.exists

    - name: "2. 대상 서버 조치 스크립트 실행"
      script: "{{ item.path }}"
      register: script_run_result
      become: yes
      loop: "{{ fix_script_files.files }}"
      environment:
        MYSQL_ENV_FILE: "{{ mysql_env_dest }}"
      when: 
        # [수정] 파일명에서 fix_를 뺀 나머지로 target_id 매칭
        - target_id is defined
        - (target_id | string) in (item.path | basename | replace('fix_', '') | replace('-', ''))
        # [분기 로직] 로키9면 mysql 스크립트만, 로키10이면 postgres 스크립트만 실행
        - ("6_db/mysql" not in (item.path | lower)) or ("Rocky9" in inventory_hostname)
        - ("6_db/postgresql" not in (item.path | lower)) or ("Rocky10" in inventory_hostname)

    # 3. 진단 결과 업데이트 (results 폴더)
    - name: "3. 결과 수집 및 JSON 저장"
      delegate_to: localhost
      become: no
      copy:
        content: "{{ item.stdout | regex_search('\\{.*\\}', multiline=True, dotall=True) | default(item.stdout, true) }}"
        # [핵심 수정] item.item.path를 사용해 실제 스크립트 이름을 가져옵니다.
        dest: "./results/{{ inventory_hostname }}_{{ item.item.path | basename | replace('.sh', '') | replace('-', '') }}.json"
      loop: "{{ script_run_result.results }}"
      when: 
        - item.stdout is defined and item.stdout | length > 0
        - not item.skipped | default(false)

    # 4. 조치 로그 전용 저장 (fix_logs 폴더)
    - name: "4. 조치 로그 저장"
      delegate_to: localhost
      become: no
      copy:
        content: "{{ item.stdout | regex_search('\\{.*\\}', multiline=True, dotall=True) | default(item.stdout, true) }}"
        dest: "./fix_logs/{{ inventory_hostname }}_fix_{{ target_id | default('all') }}.json"
      loop: "{{ script_run_result.results }}"
      when: 
        - target_id is defined
        - item.stdout is defined and item.stdout | length > 0
        - not item.skipped | default(false)

    # 5. 대시보드 즉시 반영용 
    - name: "5. 대시보드 즉시 반영"
      delegate_to: localhost
      become: no
      copy:
        content: "{{ item.stdout | regex_search('\\{.*\\}', multiline=True, dotall=True) | default(item.stdout, true) }}"
        dest: "./results/{{ inventory_hostname }}_remediated_{{ target_id | default('all') }}.json"
      loop: "{{ script_run_result.results }}"
      when: 
        - target_id is defined
        - item.stdout is defined and item.stdout | length > 0
        - not item.skipped | default(false)
